# Generated by Django 5.0.2 on 2024-02-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrer',
            new_name='career',
        ),
    ]
